#version: '3.8'

services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:latest
    container_name: property_listings_postgres
    environment:
      POSTGRES_DB: property_listings_db
      POSTGRES_USER: property_user
      POSTGRES_PASSWORD: property_password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - property_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U property_user -d property_listings_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: property_listings_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - property_network

volumes:
  postgres_data:
  redis_data:

networks:
  property_network:
    driver: bridge